import type { Product } from "@/features/products/types/product.type";

export const sampleProducts: Product[] = [
  {
    id: "P001",
    name: "Wireless Bluetooth Headphones",
    description:
      "Noise-cancelling over-ear headphones with 20 hours of battery life.",
    category: "electronics",
    selling_price: 120,
    bought_price: 80,
    unit_weight: 0.5,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 3,
    image_urls: [
      "https://plus.unsplash.com/premium_photo-1663962158789-0ab624c4f17d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8cGxhbnR8ZW58MHx8MHx8fDA%3D",
      "https://plus.unsplash.com/premium_photo-1681290358247-c160fc097bdb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8cGxhbnR8ZW58MHx8MHx8fDA%3D",
      "https://images.unsplash.com/photo-1517191434949-5e90cd67d2b6?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHBsYW50fGVufDB8fDB8fHww",
      "https://images.unsplash.com/photo-1555037015-1498966bcd7c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cGxhbnR8ZW58MHx8MHx8fDA%3D",
      "https://images.unsplash.com/photo-1597305877032-0668b3c6413a?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
  },
  {
    id: "P002",
    name: "Men’s Cotton T-Shirt",
    description: "100% cotton slim-fit T-shirt available in multiple colors.",
    category: "clothing",
    selling_price: 25,
    bought_price: 10,
    unit_weight: 0.2,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/tshirt1.jpg"],
  },
  {
    id: "P003",
    name: "Cooking Made Simple",
    description: "A beginner-friendly cookbook with 100+ easy recipes.",
    category: "books",
    selling_price: 18,
    bought_price: 7,
    unit_weight: 0.8,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/book1.jpg"],
  },
  {
    id: "P004",
    name: "Ceramic Coffee Mug",
    description: "Microwave and dishwasher safe ceramic mug (350ml).",
    category: "home",
    selling_price: 12,
    bought_price: 5,
    unit_weight: 0.4,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/mug1.jpg"],
  },
  {
    id: "P005",
    name: "Herbal Face Wash",
    description: "Natural face wash with aloe vera and neem extracts.",
    category: "clothing",
    selling_price: 15,
    bought_price: 6,
    unit_weight: 0.3,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/facewash1.jpg"],
  },
  {
    id: "P006",
    name: "Yoga Mat",
    description: "Non-slip, eco-friendly yoga mat with carrying strap.",
    category: "home",
    selling_price: 45,
    bought_price: 20,
    unit_weight: 1.2,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/yogamat1.jpg"],
  },

  // ---- 20 More Products ----
  {
    id: "P007",
    name: "Smartphone Tripod Stand",
    description: "Adjustable lightweight tripod for smartphones and cameras.",
    category: "electronics",
    selling_price: 30,
    bought_price: 15,
    unit_weight: 0.6,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/tripod1.jpg"],
  },
  {
    id: "P008",
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with USB receiver.",
    category: "electronics",
    selling_price: 20,
    bought_price: 8,
    unit_weight: 0.15,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/mouse1.jpg"],
  },
  {
    id: "P009",
    name: "Laptop Cooling Pad",
    description: "Portable cooling pad with dual fans for laptops.",
    category: "electronics",
    selling_price: 35,
    bought_price: 18,
    unit_weight: 0.9,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/coolingpad1.jpg"],
  },
  {
    id: "P010",
    name: "Bluetooth Speaker",
    description: "Compact waterproof Bluetooth speaker with deep bass.",
    category: "electronics",
    selling_price: 50,
    bought_price: 25,
    unit_weight: 0.7,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/speaker1.jpg"],
  },
  {
    id: "P011",
    name: "Casual Denim Jacket",
    description: "Classic blue denim jacket with button closure.",
    category: "clothing",
    selling_price: 60,
    bought_price: 28,
    unit_weight: 1.1,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/jacket1.jpg"],
  },
  {
    id: "P012",
    name: "Women’s Summer Dress",
    description: "Lightweight floral summer dress with short sleeves.",
    category: "clothing",
    selling_price: 40,
    bought_price: 18,
    unit_weight: 0.4,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/dress1.jpg"],
  },
  {
    id: "P013",
    name: "Men’s Running Shoes",
    description: "Breathable running shoes with cushioned soles.",
    category: "clothing",
    selling_price: 75,
    bought_price: 35,
    unit_weight: 0.9,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/shoes1.jpg"],
  },
  {
    id: "P014",
    name: "Woolen Scarf",
    description: "Soft knitted wool scarf for winter wear.",
    category: "clothing",
    selling_price: 20,
    bought_price: 8,
    unit_weight: 0.25,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/scarf1.jpg"],
  },
  {
    id: "P015",
    name: "Cotton Bedsheet Set",
    description: "King-size cotton bedsheet with 2 pillow covers.",
    category: "home",
    selling_price: 55,
    bought_price: 22,
    unit_weight: 1.5,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/bedsheet1.jpg"],
  },
  {
    id: "P016",
    name: "LED Desk Lamp",
    description: "Rechargeable LED desk lamp with adjustable brightness.",
    category: "home",
    selling_price: 35,
    bought_price: 15,
    unit_weight: 0.8,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/desklamp1.jpg"],
  },
  {
    id: "P017",
    name: "Stainless Steel Water Bottle",
    description: "Double-wall insulated bottle keeps drinks hot or cold.",
    category: "home",
    selling_price: 25,
    bought_price: 10,
    unit_weight: 0.5,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/bottle1.jpg"],
  },
  {
    id: "P018",
    name: "Non-stick Frying Pan",
    description: "Durable non-stick frying pan with heat-resistant handle.",
    category: "home",
    selling_price: 40,
    bought_price: 18,
    unit_weight: 1.3,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/fryingpan1.jpg"],
  },
  {
    id: "P019",
    name: "Fantasy Adventure Novel",
    description: "Bestselling fantasy novel with thrilling storyline.",
    category: "books",
    selling_price: 22,
    bought_price: 9,
    unit_weight: 0.7,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/book2.jpg"],
  },
  {
    id: "P020",
    name: "History of Civilizations",
    description: "Comprehensive book on the rise and fall of civilizations.",
    category: "books",
    selling_price: 28,
    bought_price: 12,
    unit_weight: 1.2,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/book3.jpg"],
  },
  {
    id: "P021",
    name: "Self-Help Guide",
    description: "Motivational book for productivity and personal growth.",
    category: "books",
    selling_price: 20,
    bought_price: 8,
    unit_weight: 0.6,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/book4.jpg"],
  },
  {
    id: "P022",
    name: "Children’s Story Book",
    description: "Illustrated bedtime stories for young readers.",
    category: "books",
    selling_price: 15,
    bought_price: 6,
    unit_weight: 0.5,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/book5.jpg"],
  },
  {
    id: "P023",
    name: "Gaming Keyboard",
    description: "RGB mechanical keyboard with customizable keys.",
    category: "electronics",
    selling_price: 90,
    bought_price: 45,
    unit_weight: 1.1,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/keyboard1.jpg"],
  },
  {
    id: "P024",
    name: "Noise-Cancelling Earbuds",
    description: "In-ear wireless earbuds with charging case.",
    category: "electronics",
    selling_price: 65,
    bought_price: 30,
    unit_weight: 0.25,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/earbuds1.jpg"],
  },
  {
    id: "P025",
    name: "Leather Wallet",
    description: "Men’s slim leather wallet with multiple compartments.",
    category: "clothing",
    selling_price: 35,
    bought_price: 15,
    unit_weight: 0.3,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/wallet1.jpg"],
  },
  {
    id: "P026",
    name: "Portable Blender",
    description: "USB rechargeable portable blender for smoothies.",
    category: "home",
    selling_price: 55,
    bought_price: 25,
    unit_weight: 1.0,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/blender1.jpg"],
  },
];
