import type { Product } from "@/features/products/types/product.type";

export const CATEGORIES = [
  { label: "Flower Seeds", value: "flower-seeds" },
  { label: "Vegetable Seeds", value: "vegetable-seeds" },
  { label: "Saplings", value: "saplings" },
  { label: "Gardening Tools", value: "gardening-tools" },
  { label: "Eco Products", value: "eco-products" },
];

export const CATEGORY_LABELS: string[] = CATEGORIES.map((cat) => cat.value);

export const sampleProducts: Product[] = [
  {
    id: "P001",
    name: "Rose Flower Seeds",
    description:
      "Premium rose flower seeds for home gardening. Easy to grow with vibrant colors.",
    category: "flower-seeds",
    selling_price: 5,
    bought_price: 2,
    unit_weight: 0.05,
    courier_charge_for_1st_kg: 3,
    courier_charge_for_other_kg: 1,
    image_urls: ["https://example.com/images/rose-seeds.jpg"],
  },
  {
    id: "P002",
    name: "Sunflower Seeds",
    description:
      "High-quality sunflower seeds that grow into tall, bright sunflowers.",
    category: "flower-seeds",
    selling_price: 4,
    bought_price: 1,
    unit_weight: 0.04,
    courier_charge_for_1st_kg: 3,
    courier_charge_for_other_kg: 1,
    image_urls: ["https://example.com/images/sunflower-seeds.jpg"],
  },
  {
    id: "P003",
    name: "Tomato Seeds",
    description:
      "Organic tomato seeds for fresh and juicy home-grown tomatoes.",
    category: "vegetable-seeds",
    selling_price: 3,
    bought_price: 1,
    unit_weight: 0.03,
    courier_charge_for_1st_kg: 3,
    courier_charge_for_other_kg: 1,
    image_urls: ["https://example.com/images/tomato-seeds.jpg"],
  },
  {
    id: "P004",
    name: "Mango Sapling",
    description:
      "Healthy mango tree sapling ready to be planted in your garden.",
    category: "saplings",
    selling_price: 15,
    bought_price: 7,
    unit_weight: 1.0,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/mango-sapling.jpg"],
  },
  {
    id: "P005",
    name: "Neem Sapling",
    description:
      "Neem tree sapling with medicinal and air-purifying properties.",
    category: "saplings",
    selling_price: 12,
    bought_price: 6,
    unit_weight: 0.9,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/neem-sapling.jpg"],
  },
  {
    id: "P006",
    name: "Eco Black Grow Bags",
    description: "Durable eco-friendly grow bags for vegetables and flowers.",
    category: "eco-products",
    selling_price: 8,
    bought_price: 4,
    unit_weight: 0.3,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/grow-bag.jpg"],
  },
  {
    id: "P007",
    name: "Organic Compost",
    description: "Nutrient-rich compost to boost plant growth naturally.",
    category: "eco-products",
    selling_price: 10,
    bought_price: 5,
    unit_weight: 2.0,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/compost.jpg"],
  },
  {
    id: "P008",
    name: "Garden Shovel",
    description: "Sturdy hand shovel for home gardening and planting.",
    category: "gardening-tools",
    selling_price: 12,
    bought_price: 6,
    unit_weight: 0.7,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/garden-shovel.jpg"],
  },
  {
    id: "P009",
    name: "Watering Can",
    description: "Eco-friendly watering can for easy irrigation.",
    category: "gardening-tools",
    selling_price: 15,
    bought_price: 7,
    unit_weight: 1.2,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/watering-can.jpg"],
  },
  {
    id: "P010",
    name: "Spinach Seeds",
    description: "Organic spinach seeds for nutrient-rich leafy greens.",
    category: "vegetable-seeds",
    selling_price: 3,
    bought_price: 1,
    unit_weight: 0.02,
    courier_charge_for_1st_kg: 3,
    courier_charge_for_other_kg: 1,
    image_urls: ["https://example.com/images/spinach-seeds.jpg"],
  },
];
