import type { Product } from "@/features/products/types/product.type";

export const sampleProducts: Product[] = [
  {
    id: "P001",
    name: "Wireless Bluetooth Headphones",
    description:
      "Noise-cancelling over-ear headphones with 20 hours of battery life.",
    category: "electronics",
    selling_price: 120,
    bought_price: 80,
    unit_weight: 0.5,
    courier_charge_for_1st_kg: 5,
    courier_charge_for_other_kg: 3,
    image_urls: [
      "https://example.com/images/headphones1.jpg",
      "https://example.com/images/headphones2.jpg",
    ],
  },
  {
    id: "P002",
    name: "Men’s Cotton T-Shirt",
    description: "100% cotton slim-fit T-shirt available in multiple colors.",
    category: "books",
    selling_price: 25,
    bought_price: 10,
    unit_weight: 0.2,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/tshirt1.jpg"],
  },
  {
    id: "P003",
    name: "Cooking Made Simple",
    description: "A beginner-friendly cookbook with 100+ easy recipes.",
    category: "books",
    selling_price: 18,
    bought_price: 7,
    unit_weight: 0.8,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/book1.jpg"],
  },
  {
    id: "P004",
    name: "Ceramic Coffee Mug",
    description: "Microwave and dishwasher safe ceramic mug (350ml).",
    category: "home",
    selling_price: 12,
    bought_price: 5,
    unit_weight: 0.4,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/mug1.jpg"],
  },
  {
    id: "P005",
    name: "Herbal Face Wash",
    description: "Natural face wash with aloe vera and neem extracts.",
    category: "clothing",
    selling_price: 15,
    bought_price: 6,
    unit_weight: 0.3,
    courier_charge_for_1st_kg: 4,
    courier_charge_for_other_kg: 2,
    image_urls: ["https://example.com/images/facewash1.jpg"],
  },
  {
    id: "P006",
    name: "Yoga Mat",
    description: "Non-slip, eco-friendly yoga mat with carrying strap.",
    category: "electronics",
    selling_price: 45,
    bought_price: 20,
    unit_weight: 1.2,
    courier_charge_for_1st_kg: 6,
    courier_charge_for_other_kg: 3,
    image_urls: ["https://example.com/images/yogamat1.jpg"],
  },
];
